Refactor Kandinsky endpoint into diffusers
runpod-workers/worker-kandinsky pull request #2
Opened 2023-06-11 20:46 UTC by kodxana

Changes:
- Switched Kandinsky endpoint into Diffusers pipeline
- Added xformers for memory optimization
- Added seed parameter default is -1 (random)
- Refactored model_fetcher.py to include Diffusers base model

Overlay Diffusers brings much faster image generation compared to orginal implementation.

2023-06-12 21:14 UTC, justinmerrell commented on Dockerfile
> +RUN pip install diffusers transformers accelerate
Any reason these were not part of the requirements.txt?

2023-06-12 22:07 UTC, justinmerrell requested changes
Looks good overall, just curious about the requirements.txt

2023-06-13 15:44 UTC, kodxana commented on src/rp_handler.py
> +    image.save(image_path)
Added:
- num_images to schema (also removed old batch_size)

2023-06-13 15:44 UTC, kodxana commented on builder/model_fetcher.py
> +    pipe_prior = DiffusionPipeline.from_pretrained("kandinsky-community/kandinsky-2-1-prior",
Is same model just in Diffusion format

2023-06-13 15:45 UTC, kodxana commented on Dockerfile
> +RUN pip install diffusers transformers accelerate
Moved diffusers transformers accelerate to requirements.txt with locked minimum version of diffusers

2023-06-14 20:38 UTC, justinmerrell requested changes

2023-06-14 20:38 UTC, justinmerrell commented on builder/requirements.txt
Need to version lock:

xformers
transformers
accelerate

2023-06-15 00:59 UTC, merged